name: CI of angular
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Setup
        run: npm i
      - name: Test
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
