name: CI of angular
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: ci
        run: npm ci
      - name: install chrome
        run: npm install chromedriver --chromedriver_version=LATEST_89
      - name: Test
        run: npm test
