name: CI of angular
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm cache clean --force
      - run: npm i -g @angular/cli
      - name: Setup dependences
        run: npm i -g npm-install-peers
      - name: Test
        run: npm test
